<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sparc.ProcessTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sparc.Core\Sparc.Core.csproj" />
    <ProjectReference Include="..\..\src\Sparc.Client\Sparc.Client.csproj" />
    <ProjectReference Include="..\..\src\Sparc.WindowsMemoryMapped\Sparc.WindowsMemoryMapped.csproj" />
    <ProjectReference Include="..\..\tools\Sparc.Producer\Sparc.Producer.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\tools\Sparc.Consumer\Sparc.Consumer.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
