<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>RingBuffer.Benchmarks</RootNamespace>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="BenchmarkDotNet.Attributes" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RingBuffer.Core\RingBuffer.Core.csproj" />
    <ProjectReference Include="..\..\src\RingBuffer.SharedMemory\RingBuffer.SharedMemory.csproj" />
    <ProjectReference Include="..\..\src\RingBuffer.Producer\RingBuffer.Producer.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\RingBuffer.Consumer\RingBuffer.Consumer.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
