<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RootNamespace>Sparc.YarpProxy</RootNamespace>
    <AssemblyName>Sparc.YarpProxy</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Sparc.YarpShared\YarpCaptureProtocol.cs" Link="YarpCaptureProtocol.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sparc.Core\Sparc.Core.csproj" />
    <ProjectReference Include="..\..\src\Sparc.WindowsMemoryMapped\Sparc.WindowsMemoryMapped.csproj" />
  </ItemGroup>

</Project>
