<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>RingBuffer.UnitTests</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RingBuffer.Core\RingBuffer.Core.csproj" />
    <ProjectReference Include="..\..\src\RingBuffer.Client\RingBuffer.Client.csproj" />
    <ProjectReference Include="..\..\src\Ipc.WindowsMemoryMapped\Ipc.WindowsMemoryMapped.csproj" />
  </ItemGroup>

</Project>
