<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sparc.YarpConsumer</RootNamespace>
    <AssemblyName>Sparc.YarpConsumer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Sparc.YarpShared\YarpCaptureProtocol.cs" Link="YarpCaptureProtocol.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sparc.Core\Sparc.Core.csproj" />
    <ProjectReference Include="..\..\src\Sparc.WindowsMemoryMapped\Sparc.WindowsMemoryMapped.csproj" />
  </ItemGroup>

</Project>
