<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>RingBuffer.Consumer</RootNamespace>
    <AssemblyName>RingBuffer.Consumer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\CommandLine.cs" Link="CommandLine.cs" />
    <Compile Include="..\Shared\Cli.cs" Link="Cli.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RingBuffer.Core\RingBuffer.Core.csproj" />
    <ProjectReference Include="..\RingBuffer.Client\RingBuffer.Client.csproj" />
    <ProjectReference Include="..\Ipc.WindowsMemoryMapped\Ipc.WindowsMemoryMapped.csproj" />
  </ItemGroup>

</Project>
